### ISSUE TITLE
Create Webpack Build for API

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#10]
Right now we are starting the site simply by running node on the `./src` directory. We have no import statements. We want to incorporate a build process for the API that uses webapck and babel. We also need to be able to watch the files and re-run the api when the source changes.

## TODO

- [ ] Upgrade `./src` modules to use import statements
- [ ] Build `./src` to `./dist` (or preferred build folder name)
- [ ] Run app from `./dist` (or preferred build folder name)
- [ ] development: watch source, rebuild and restart API automatically
