### ISSUE TITLE
Get started with Application Steps

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#17]
Now that we have authorization and saving, let's get started building application steps. A user should be able to view wheater on not they have finished each application step or not.

## TODO

- [x] Add `User` resolver for `application`
- [x] Resolve `dateStarted`
- [x] Resolve `dateOfInjury`
- [x] Resolve `lastSave`
- [x] Resolve `steps` __typename
- [x] Resolve `steps` started
- [x] Resolve `steps` url

## Goal Query

```graphql
query myApplication {
  me {
    name{
      first
      last
    }
    application {
      dateStarted
      dateOfInjury
      lastSave
      steps {
        type:__typename
        started
        url
      }
    }
  }
}
```
