### ISSUE TITLE
Break out multiple `save` functions

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#36]
We are going to break down save mutations per form, and handle saving funding categories as well. 

### TODO

- [x] Review Funding Categories
- [x] Revamp Schema to Reflect New save solution
- [x] Strip out admin into a separate schema
- [x] Strip out old Save Solution
- [x] Stub Save Resolvers

related #25
