### ISSUE TITLE
Upgrade to `@apollo/react-hooks`

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#37]
We are going to change our Apollo approach to use the new hooks library.

### TODO

- [x] Strip out all custom hooks and npms
- [x] Add `@apollo/react-hooks`
- [x] Upgrade the Apollo Client
- [x] Upgrade `createAccount` form and functionality
- [x] Handle `createAccount` errors
- [x] Add `name` field to mongo collection so we can see user names
- [x] Remove `FullName` object from Graphql
- [ ] Upgrade `login` form and functionality
- [ ] Handle `login` errors
- [x] Remove, or comment out any application or me queries
- [ ] Make sure no refresh is required to see changes
