### ISSUE TITLE
Handle application General Information on the API 

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#40]
Build the Backend mutation and queries necessary to handle saving and loading an application's General Information.

### TODO

- [x] **api**: Code Resolver to Save General Info
- [x] **api**: Build and Test Save General Info Mutation
- [x] **api**: Build and Test Save General Info Query
- [x] **api**: Build enum queries that are necessary to populate ddls

necessary to complete related issue #38 
necessary to complete related issue #41
