### ISSUE TITLE
Save and Load Data on General Information Form

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#41]
It's time to make those form fields work. We want to create text and drop down elements that automatically save the current general information when the user leaves the field.

### TODO

- [ ] **client**: Form Fields Save Data and update cache
- [ ] **client**: Populate drop downs from query.
- [ ] **client**: Drop Down Lists Save Data and update cache
- [ ] **client**: Form auto-populates with saved data

This is necessary to complete related issue #38
