### ISSUE TITLE
Create Polished Styles for General Information Form

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#42]
We need to make the General Information Form look good with CSS solutions that are reusable and easy to follow when creating future forms.

### TODOS

- [ ] **client**: Polish Form By adding form sections
- [ ] **client**: Incorporate Material UI Drop Down Components
- [ ] **style**: Mobile First Responsive Form
- [ ] **style**: Mobile First Responsive Progress Placeholder
- [ ] **style**: Previous and Next Buttons
- [ ] **style**: Final Polish of General Information form

Necessary to complete related issue #38
