### ISSUE TITLE
Handle Form Errors

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#43]
It's time to help our users fill out the form with success indicators, error handling, and tool tips. Whatever solution that we design here should be reusable across other forms.

### TODO

- [ ] **client**: Text Areas Display Validation Errors
- [ ] **client**: Text Areas Display Network Errors
- [ ] **client**: Text areas indicate successful saves
- [ ] **client**: Text areas have description tool tips
- [ ] **client**: Finalize Reusable Text Areas
- [ ] **client**: Finalize Reusable Drop Down Lists

Necessary to complete related issue #38
