### ISSUE TITLE
Incorporate API Testing

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/athlete-application#8]
We need a way to incorporate quality assurance into our build process. At minimum, we need integration tests for the API. That means running the API and testing queries and mutations and verifying results using a mock database.

We also need to incorporate some sort of CI so we can verify branches and pull requests and automatically deploy.

### TODO

- [ ] Mock or Test DB solution 
- [ ] Test Authorization Flow
- [ ] Test `save` mutation
- [ ] Test progress queries
- [ ] Test remaining queries
- [ ] Incorporate testing into CI
